[project]
name = "deep-agentic-rag-monorepo"
version = "0.1.0"
description = "A repository containing multiple agentic applications."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11,<4.0"
dependencies = [
    # Dependencies for both projects
    "langgraph>=0.2.6",
    "langchain>=0.2.14",
    "langchain-anthropic>=0.1.23", # from deepagents
    "langchain[openai]",
    "langchain-community",
    "langchain-text-splitters",
    "python-dotenv",
    "unstructured[md]",
    "langgraph-cli[inmem]",
]


[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["deepagents", "agentic_rag"]
[tool.setuptools.package-dir]
"deepagents" = "src/deepagents"
"agentic_rag" = "src/agentic_rag"

[tool.setuptools.package-data]
"*" = ["py.typed"]
